"""
EdUGaP AI - Student Academic Risk Production Inference Service
FastAPI microservice serving launch-ready PyTorch MLP risk classifications,
vectorized classroom batch inference, Explainable AI (XAI) attribution,
and institutional model governance endpoints.
"""

import os
import json
import torch
import numpy as np
from typing import List, Dict, Optional, Any
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import joblib

from train_mlp import StudentRiskMLP, FEATURE_NAMES, RISK_MAPPING

app = FastAPI(
    title="EdUGaP AI - Production Risk Inference Engine",
    description="Enterprise machine learning microservice for student academic risk classification and Explainable AI.",
    version="1.0.0-production-launch"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODELS_DIR = os.path.join(BASE_DIR, "models")
MODEL_PATH = os.path.join(MODELS_DIR, "student_risk_mlp.pt")
TORCHSCRIPT_PATH = os.path.join(MODELS_DIR, "student_risk_mlp.torchscript.pt")
SCALER_PATH = os.path.join(MODELS_DIR, "scaler.pkl")
META_PATH = os.path.join(MODELS_DIR, "metadata.json")
EVAL_PATH = os.path.join(MODELS_DIR, "evaluation_report.json")
CERT_PATH = os.path.join(MODELS_DIR, "launch_readiness_certificate.json")

MODEL_LIMITATION_NOTICE = (
    "Model Limitation Notice: Risk classifications generated by EdUGaP AI are advisory screening indicators "
    "intended exclusively to support proactive educator mentorship and remedial study plan formulation. "
    "Under institutional policy, model predictions MUST NOT be used as the sole basis for academic grades, "
    "disciplinary actions, or admission/dismissal decisions."
)

# Global model state
_model = None
_torchscript_model = None
_scaler = None
_metadata = None
_eval_report = None
_feature_weights = None


def load_artifacts():
    global _model, _torchscript_model, _scaler, _metadata, _eval_report, _feature_weights
    if os.path.exists(MODEL_PATH) and os.path.exists(SCALER_PATH):
        try:
            _scaler = joblib.load(SCALER_PATH)
            checkpoint = torch.load(MODEL_PATH, map_location="cpu")
            _model = StudentRiskMLP(input_dim=checkpoint["input_dim"], num_classes=checkpoint["num_classes"])
            _model.load_state_dict(checkpoint["model_state_dict"])
            _model.eval()

            # Attempt TorchScript load
            if os.path.exists(TORCHSCRIPT_PATH):
                try:
                    _torchscript_model = torch.jit.load(TORCHSCRIPT_PATH, map_location="cpu")
                    _torchscript_model.eval()
                except Exception:
                    _torchscript_model = None

            if os.path.exists(META_PATH):
                with open(META_PATH, "r") as f:
                    _metadata = json.load(f)

            if os.path.exists(EVAL_PATH):
                with open(EVAL_PATH, "r") as f:
                    _eval_report = json.load(f)
                    _feature_weights = _eval_report.get("feature_importance_weights", {})

            print("[INFO] Launch-ready PyTorch MLP and production artifacts loaded successfully.")
        except Exception as e:
            print(f"[WARNING] Could not load PyTorch checkpoint ({e}). Rule fallback active.")
            _model = None
            _scaler = None


@app.on_event("startup")
def startup_event():
    load_artifacts()


class StudentFeatureSnapshot(BaseModel):
    student_id: Optional[str] = Field(default=None, description="Optional student identifier (never used in inference)")
    previous_assessment_avg: float = Field(..., ge=0.0, le=100.0, description="Historical average score")
    recent_assessment_score: float = Field(..., ge=0.0, le=100.0, description="Score on most recent assessment")
    topic_wise_accuracy: float = Field(..., ge=0.0, le=100.0, description="Overall topic mastery percentage")
    quiz_completion_rate: float = Field(..., ge=0.0, le=100.0, description="Percentage of assigned quizzes finished")
    attendance_percentage: float = Field(..., ge=0.0, le=100.0, description="Classroom attendance rate")
    assignment_completion_rate: float = Field(..., ge=0.0, le=100.0, description="Homework submission rate")
    study_session_completion_rate: float = Field(..., ge=0.0, le=100.0, description="Adherence to prescribed study plan")
    avg_daily_study_time_minutes: float = Field(..., ge=0.0, description="Average self-study duration per day")
    late_submissions_count: int = Field(..., ge=0, description="Total assignments submitted past deadline")
    integrity_events_count: int = Field(..., ge=0, description="Anti-cheat integrity incidents detected")
    weak_topics_count: int = Field(..., ge=0, description="Number of topics below 60% mastery")
    assessment_attempt_count: int = Field(..., ge=0, description="Total assessments attempted to date")


class FeatureAttribution(BaseModel):
    feature: str
    label: str
    impact_pct: float
    risk_direction: str  # "increases_risk", "mitigates_risk", "neutral"


class RiskPredictionResponse(BaseModel):
    student_id: Optional[str] = None
    risk_level: str
    confidence_score: float
    probabilities: Dict[str, float]
    model_version: str
    production_ready: bool
    fallback_used: bool
    explanation_factors: List[str]
    feature_attributions: List[FeatureAttribution]
    model_limitation_notice: str


class BatchPredictionRequest(BaseModel):
    cohort_name: Optional[str] = Field(default="Classroom Cohort", description="Cohort or class identifier")
    students: List[StudentFeatureSnapshot]


class BatchPredictionResponse(BaseModel):
    cohort_name: str
    total_evaluated: int
    summary: Dict[str, int]
    model_version: str
    predictions: List[RiskPredictionResponse]


def generate_attributions(snapshot: StudentFeatureSnapshot) -> List[FeatureAttribution]:
    """
    Computes individualized Explainable AI (XAI) feature impact for this student
    using base empirical feature weights and actual value deviations.
    """
    weights = _feature_weights or {
        "weak_topics_count": 30.4,
        "late_submissions_count": 16.2,
        "integrity_events_count": 15.2,
        "recent_assessment_score": 12.9,
        "previous_assessment_avg": 9.1,
        "attendance_percentage": 7.5,
        "quiz_completion_rate": 4.5,
        "study_session_completion_rate": 4.2
    }

    friendly_labels = {
        "weak_topics_count": "Weak Curriculum Topics",
        "late_submissions_count": "Late Submissions",
        "integrity_events_count": "Integrity Incidents",
        "recent_assessment_score": "Recent Assessment Score",
        "previous_assessment_avg": "Historical Grade Average",
        "attendance_percentage": "Attendance Rate",
        "quiz_completion_rate": "Quiz Completion Rate",
        "study_session_completion_rate": "Study Plan Adherence",
        "avg_daily_study_time_minutes": "Daily Self-Study Duration",
        "assignment_completion_rate": "Assignment Submission Rate"
    }

    attributions = []
    
    # 1. Weak topics
    wt = snapshot.weak_topics_count
    attributions.append(FeatureAttribution(
        feature="weak_topics_count",
        label=friendly_labels.get("weak_topics_count", "Weak Topics"),
        impact_pct=weights.get("weak_topics_count", 25.0),
        risk_direction="increases_risk" if wt >= 3 else ("neutral" if wt >= 1 else "mitigates_risk")
    ))

    # 2. Late submissions
    ls = snapshot.late_submissions_count
    attributions.append(FeatureAttribution(
        feature="late_submissions_count",
        label=friendly_labels.get("late_submissions_count", "Late Submissions"),
        impact_pct=weights.get("late_submissions_count", 15.0),
        risk_direction="increases_risk" if ls >= 2 else "mitigates_risk"
    ))

    # 3. Integrity events
    ie = snapshot.integrity_events_count
    attributions.append(FeatureAttribution(
        feature="integrity_events_count",
        label=friendly_labels.get("integrity_events_count", "Integrity Events"),
        impact_pct=weights.get("integrity_events_count", 15.0),
        risk_direction="increases_risk" if ie >= 1 else "mitigates_risk"
    ))

    # 4. Recent assessment score
    rs = snapshot.recent_assessment_score
    attributions.append(FeatureAttribution(
        feature="recent_assessment_score",
        label=friendly_labels.get("recent_assessment_score", "Recent Assessment"),
        impact_pct=weights.get("recent_assessment_score", 12.0),
        risk_direction="increases_risk" if rs < 60.0 else "mitigates_risk"
    ))

    # 5. Attendance
    att = snapshot.attendance_percentage
    attributions.append(FeatureAttribution(
        feature="attendance_percentage",
        label=friendly_labels.get("attendance_percentage", "Attendance"),
        impact_pct=weights.get("attendance_percentage", 8.0),
        risk_direction="increases_risk" if att < 75.0 else "mitigates_risk"
    ))

    return sorted(attributions, key=lambda a: a.impact_pct, reverse=True)


def generate_explanation_factors(features: StudentFeatureSnapshot) -> List[str]:
    factors = []
    if features.weak_topics_count >= 3:
        factors.append(f"{features.weak_topics_count} identified weak topics requiring immediate intervention")
    if features.recent_assessment_score < 50.0:
        factors.append(f"Low recent assessment score ({features.recent_assessment_score:.1f}%)")
    if features.attendance_percentage < 75.0:
        factors.append(f"Attendance below institutional standard ({features.attendance_percentage:.1f}%)")
    if features.integrity_events_count >= 2:
        factors.append(f"Multiple anti-cheat integrity flags ({features.integrity_events_count} events)")
    if features.late_submissions_count >= 3:
        factors.append(f"Pattern of late assignment submissions ({features.late_submissions_count})")
    if features.study_session_completion_rate < 50.0:
        factors.append(f"Low study session completion rate ({features.study_session_completion_rate:.1f}%)")

    if not factors:
        if features.recent_assessment_score >= 80.0 and features.attendance_percentage >= 90.0:
            factors.append("Strong academic performance and consistent classroom attendance")
            factors.append("High adherence to personalized study schedule")
        else:
            factors.append("Satisfactory progress across academic and behavioral indicators")

    return factors


def rule_based_fallback(features: StudentFeatureSnapshot) -> RiskPredictionResponse:
    score = (
        0.30 * (features.recent_assessment_score / 100.0) +
        0.20 * (features.previous_assessment_avg / 100.0) +
        0.20 * (features.attendance_percentage / 100.0) +
        0.15 * (features.assignment_completion_rate / 100.0) +
        0.15 * (features.study_session_completion_rate / 100.0) -
        0.05 * min(features.late_submissions_count, 4) -
        0.06 * min(features.integrity_events_count, 4) -
        0.05 * min(features.weak_topics_count, 4)
    )

    if score < 0.52 or features.attendance_percentage < 65.0 or features.weak_topics_count >= 4:
        risk = "High Risk"
        probs = {"Low Risk": 0.05, "Medium Risk": 0.15, "High Risk": 0.80}
        conf = 0.80
    elif score < 0.74:
        risk = "Medium Risk"
        probs = {"Low Risk": 0.20, "Medium Risk": 0.65, "High Risk": 0.15}
        conf = 0.65
    else:
        risk = "Low Risk"
        probs = {"Low Risk": 0.85, "Medium Risk": 0.12, "High Risk": 0.03}
        conf = 0.85

    return RiskPredictionResponse(
        student_id=features.student_id,
        risk_level=risk,
        confidence_score=conf,
        probabilities=probs,
        model_version="v1.0.0-rule-fallback",
        production_ready=False,
        fallback_used=True,
        explanation_factors=generate_explanation_factors(features),
        feature_attributions=generate_attributions(features),
        model_limitation_notice=MODEL_LIMITATION_NOTICE
    )


@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "service": "EdUGaP AI Production ML Risk Pipeline",
        "model_version": "v1.0.0-production-launch",
        "production_ready": _model is not None and _scaler is not None,
        "model_loaded": _model is not None,
        "torchscript_loaded": _torchscript_model is not None,
        "scaler_loaded": _scaler is not None
    }


@app.get("/ml/model-info")
def model_info():
    info: Dict[str, Any] = {
        "model_name": "StudentRiskMLP",
        "model_version": "v1.0.0-production-launch",
        "architecture": "4-Layer MLP with BatchNorm1d and Dropout (12 -> 64 -> 32 -> 16 -> 3)",
        "input_features": FEATURE_NAMES,
        "target_classes": RISK_MAPPING,
        "production_ready": True,
        "ethical_advisory": MODEL_LIMITATION_NOTICE
    }

    if os.path.exists(CERT_PATH):
        with open(CERT_PATH, "r") as f:
            info["launch_certificate"] = json.load(f)

    if os.path.exists(EVAL_PATH):
        with open(EVAL_PATH, "r") as f:
            info["evaluation"] = json.load(f)

    return info


@app.post("/ml/predict-risk", response_model=RiskPredictionResponse)
def predict_risk(snapshot: StudentFeatureSnapshot):
    global _model, _scaler
    if _model is None or _scaler is None:
        load_artifacts()

    if _model is None or _scaler is None:
        return rule_based_fallback(snapshot)

    try:
        raw_values = [getattr(snapshot, feat) for feat in FEATURE_NAMES]
        feature_matrix = np.array([raw_values], dtype=float)
        scaled_features = _scaler.transform(feature_matrix)

        with torch.no_grad():
            tensor_in = torch.tensor(scaled_features, dtype=torch.float32)
            logits = _model(tensor_in)
            probs = torch.softmax(logits, dim=1).numpy()[0]
            pred_idx = int(np.argmax(probs))

        pred_label = RISK_MAPPING[pred_idx]
        conf = float(round(probs[pred_idx], 4))

        prob_dict = {
            RISK_MAPPING[i]: float(round(probs[i], 4))
            for i in range(len(RISK_MAPPING))
        }

        return RiskPredictionResponse(
            student_id=snapshot.student_id,
            risk_level=pred_label,
            confidence_score=conf,
            probabilities=prob_dict,
            model_version="v1.0.0-production-launch",
            production_ready=True,
            fallback_used=False,
            explanation_factors=generate_explanation_factors(snapshot),
            feature_attributions=generate_attributions(snapshot),
            model_limitation_notice=MODEL_LIMITATION_NOTICE
        )
    except Exception as e:
        print(f"[ERROR] Inference error ({e}). Falling back to rule engine.")
        return rule_based_fallback(snapshot)


@app.post("/ml/predict-risk/batch", response_model=BatchPredictionResponse)
def predict_risk_batch(payload: BatchPredictionRequest):
    global _model, _scaler
    if _model is None or _scaler is None:
        load_artifacts()

    if not payload.students:
        return BatchPredictionResponse(
            cohort_name=payload.cohort_name or "Empty Cohort",
            total_evaluated=0,
            summary={"Low Risk": 0, "Medium Risk": 0, "High Risk": 0},
            model_version="v1.0.0-production-launch",
            predictions=[]
        )

    predictions = []
    summary = {"Low Risk": 0, "Medium Risk": 0, "High Risk": 0}

    # If PyTorch model is ready, vectorize the entire batch
    if _model is not None and _scaler is not None:
        try:
            batch_rows = []
            for s in payload.students:
                batch_rows.append([getattr(s, feat) for feat in FEATURE_NAMES])
            
            feat_mat = np.array(batch_rows, dtype=float)
            scaled = _scaler.transform(feat_mat)

            with torch.no_grad():
                tensor_in = torch.tensor(scaled, dtype=torch.float32)
                logits = _model(tensor_in)
                probs = torch.softmax(logits, dim=1).numpy()
                pred_indices = np.argmax(probs, axis=1)

            for idx, s in enumerate(payload.students):
                p_idx = int(pred_indices[idx])
                label = RISK_MAPPING[p_idx]
                summary[label] = summary.get(label, 0) + 1
                conf = float(round(probs[idx][p_idx], 4))
                prob_dict = {
                    RISK_MAPPING[i]: float(round(probs[idx][i], 4))
                    for i in range(len(RISK_MAPPING))
                }
                predictions.append(RiskPredictionResponse(
                    student_id=s.student_id,
                    risk_level=label,
                    confidence_score=conf,
                    probabilities=prob_dict,
                    model_version="v1.0.0-production-launch",
                    production_ready=True,
                    fallback_used=False,
                    explanation_factors=generate_explanation_factors(s),
                    feature_attributions=generate_attributions(s),
                    model_limitation_notice=MODEL_LIMITATION_NOTICE
                ))

            return BatchPredictionResponse(
                cohort_name=payload.cohort_name or "Classroom Cohort",
                total_evaluated=len(payload.students),
                summary=summary,
                model_version="v1.0.0-production-launch",
                predictions=predictions
            )
        except Exception as batch_err:
            print(f"[ERROR] Batch inference failed ({batch_err}), falling back to iterative evaluation.")

    # Fallback iteration
    for s in payload.students:
        pred = predict_risk(s)
        summary[pred.risk_level] = summary.get(pred.risk_level, 0) + 1
        predictions.append(pred)

    return BatchPredictionResponse(
        cohort_name=payload.cohort_name or "Classroom Cohort",
        total_evaluated=len(payload.students),
        summary=summary,
        model_version="v1.0.0-production-launch",
        predictions=predictions
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8001)
