// ============================================================================
// EdUGaP AI - Production Machine Learning Client
// Integrates Next.js with the Launch-Ready FastAPI PyTorch MLP Risk Service
// Supports single inference, high-throughput cohort batch evaluation, and XAI
// ============================================================================

import { StudentFeatureSnapshot, RiskPrediction, FeatureAttribution } from '@/lib/types';

const FASTAPI_URL = process.env.ML_SERVICE_URL || 'http://127.0.0.1:8001';

export const MODEL_LIMITATION_NOTICE =
  'Model Limitation Notice: Risk classifications generated by EdUGaP AI are advisory screening indicators ' +
  'intended exclusively to support proactive educator mentorship and remedial study plan formulation. ' +
  'Under institutional policy, model predictions MUST NOT be used as the sole basis for academic grades, ' +
  'disciplinary actions, or admission/dismissal decisions.';

export interface ModelInfoResponse {
  model_name: string;
  model_version: string;
  architecture: string;
  input_features: string[];
  production_ready: boolean;
  ethical_advisory: string;
  launch_certificate?: {
    certificate_name: string;
    model_version: string;
    certification_date: string;
    status: string;
    metrics_summary: {
      test_accuracy: string;
      macro_f1: string;
      single_latency: string;
      batch_50_latency: string;
      test_records_evaluated: number;
    };
    top_risk_drivers: [string, number][];
  };
  evaluation?: {
    accuracy_pct: number;
    macro_f1: number;
    test_records: number;
    latency_benchmarks: {
      single_prediction_latency_ms: number;
      classroom_batch_50_latency_ms: number;
      throughput_predictions_per_sec: number;
    };
  };
}

export interface BatchRiskResult {
  cohortName: string;
  totalEvaluated: number;
  summary: {
    'Low Risk': number;
    'Medium Risk': number;
    'High Risk': number;
  };
  modelVersion: string;
  predictions: RiskPrediction[];
}

/**
 * Predict risk category and Explainable AI feature attributions for a single student.
 */
export async function predictStudentRisk(
  features: StudentFeatureSnapshot
): Promise<RiskPrediction> {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3500); // 3.5s timeout

    const res = await fetch(`${FASTAPI_URL}/ml/predict-risk`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(features),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (res.ok) {
      const data = await res.json();
      return {
        studentId: features.studentId || features.id || 'unknown',
        risk_level: data.risk_level,
        confidence_score: data.confidence_score,
        probabilities: data.probabilities,
        top_risk_factors: data.explanation_factors || [],
        feature_attributions: data.feature_attributions || [],
        model_version: data.model_version || 'v1.0.0-production-launch',
        production_ready: data.production_ready ?? true,
        fallback_used: data.fallback_used ?? false,
        model_limitation_notice: data.model_limitation_notice || MODEL_LIMITATION_NOTICE,
        createdAt: new Date().toISOString(),
      };
    }
  } catch (err) {
    // Falls back to local deterministic rule engine
  }

  return evaluateRuleBasedFallback(features);
}

/**
 * High-throughput vectorized batch prediction for an entire classroom or department cohort.
 */
export async function predictCohortRisk(
  cohortName: string,
  students: StudentFeatureSnapshot[]
): Promise<BatchRiskResult> {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 6000);

    const res = await fetch(`${FASTAPI_URL}/ml/predict-risk/batch`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        cohort_name: cohortName,
        students,
      }),
      signal: controller.signal,
    });

    clearTimeout(timeoutId);

    if (res.ok) {
      const data = await res.json();
      return {
        cohortName: data.cohort_name,
        totalEvaluated: data.total_evaluated,
        summary: data.summary,
        modelVersion: data.model_version,
        predictions: data.predictions.map((p: any) => ({
          studentId: p.student_id || 'unknown',
          risk_level: p.risk_level,
          confidence_score: p.confidence_score,
          probabilities: p.probabilities,
          top_risk_factors: p.explanation_factors || [],
          feature_attributions: p.feature_attributions || [],
          model_version: p.model_version,
          production_ready: p.production_ready ?? true,
          fallback_used: p.fallback_used ?? false,
          model_limitation_notice: p.model_limitation_notice,
          createdAt: new Date().toISOString(),
        })),
      };
    }
  } catch (err) {
    // Fallback batch iteration
  }

  const predictions = students.map((s) => evaluateRuleBasedFallback(s));
  const summary = { 'Low Risk': 0, 'Medium Risk': 0, 'High Risk': 0 };
  predictions.forEach((p) => {
    const key = p.risk_level as 'Low Risk' | 'Medium Risk' | 'High Risk';
    if (summary[key] !== undefined) summary[key]++;
  });

  return {
    cohortName,
    totalEvaluated: students.length,
    summary,
    modelVersion: 'v1.0.0-rule-fallback',
    predictions,
  };
}

/**
 * Fetches verified launch certification and accuracy metrics from the FastAPI service.
 */
export async function getModelInfo(): Promise<ModelInfoResponse | null> {
  try {
    const res = await fetch(`${FASTAPI_URL}/ml/model-info`, {
      next: { revalidate: 60 },
    });
    if (res.ok) {
      return await res.json();
    }
  } catch (err) {
    // offline or unreachable
  }
  return null;
}

/**
 * Local transparent rule-based fallback when ML microservice is disconnected.
 */
export function evaluateRuleBasedFallback(
  features: StudentFeatureSnapshot
): RiskPrediction {
  const academic =
    0.25 * (features.recent_assessment_score / 100.0) +
    0.2 * (features.previous_assessment_avg / 100.0) +
    0.15 * (features.attendance_percentage / 100.0) +
    0.15 * (features.assignment_completion_rate / 100.0) +
    0.15 * (features.quiz_completion_rate / 100.0) +
    0.1 * (features.study_session_completion_rate / 100.0);

  const penalty =
    0.03 * Math.min(features.late_submissions_count, 4) +
    0.04 * Math.min(features.integrity_events_count, 4) +
    0.03 * Math.min(features.weak_topics_count, 4);

  const composite = Math.max(0, Math.min(1, academic - penalty));

  let riskLevel: 'Low Risk' | 'Medium Risk' | 'High Risk' = 'Low Risk';
  let conf = 0.85;
  let probs = { 'Low Risk': 0.85, 'Medium Risk': 0.12, 'High Risk': 0.03 };

  if (
    composite < 0.5 ||
    features.attendance_percentage < 60 ||
    features.weak_topics_count >= 4
  ) {
    riskLevel = 'High Risk';
    conf = 0.91;
    probs = { 'Low Risk': 0.03, 'Medium Risk': 0.06, 'High Risk': 0.91 };
  } else if (composite < 0.72) {
    riskLevel = 'Medium Risk';
    conf = 0.74;
    probs = { 'Low Risk': 0.18, 'Medium Risk': 0.74, 'High Risk': 0.08 };
  }

  const factors: string[] = [];
  if (features.weak_topics_count >= 3) {
    factors.push(`${features.weak_topics_count} identified weak topics requiring intervention`);
  }
  if (features.recent_assessment_score < 50) {
    factors.push(`Recent assessment deficit (${features.recent_assessment_score}%)`);
  }
  if (features.attendance_percentage < 75) {
    factors.push(`Attendance below institutional target (${features.attendance_percentage}%)`);
  }
  if (features.integrity_events_count >= 2) {
    factors.push(`${features.integrity_events_count} anti-cheat integrity flags recorded`);
  }
  if (features.late_submissions_count >= 3) {
    factors.push(`${features.late_submissions_count} late assignment submissions`);
  }

  if (factors.length === 0) {
    if (features.recent_assessment_score >= 80 && features.attendance_percentage >= 90) {
      factors.push('Consistent high assessment scores and regular attendance');
      factors.push('High study schedule compliance');
    } else {
      factors.push('Satisfactory progress across academic and behavioral metrics');
    }
  }

  const attributions: FeatureAttribution[] = [
    {
      feature: 'weak_topics_count',
      label: 'Weak Curriculum Topics',
      impact_pct: 30.4,
      risk_direction: features.weak_topics_count >= 3 ? 'increases_risk' : 'mitigates_risk',
    },
    {
      feature: 'late_submissions_count',
      label: 'Late Submissions',
      impact_pct: 16.2,
      risk_direction: features.late_submissions_count >= 2 ? 'increases_risk' : 'mitigates_risk',
    },
    {
      feature: 'integrity_events_count',
      label: 'Integrity Incidents',
      impact_pct: 15.2,
      risk_direction: features.integrity_events_count >= 1 ? 'increases_risk' : 'mitigates_risk',
    },
    {
      feature: 'recent_assessment_score',
      label: 'Recent Assessment Score',
      impact_pct: 12.9,
      risk_direction: features.recent_assessment_score < 60 ? 'increases_risk' : 'mitigates_risk',
    },
    {
      feature: 'attendance_percentage',
      label: 'Attendance Rate',
      impact_pct: 7.5,
      risk_direction: features.attendance_percentage < 75 ? 'increases_risk' : 'mitigates_risk',
    },
  ];

  return {
    studentId: features.studentId || features.id || 'unknown',
    risk_level: riskLevel,
    confidence_score: conf,
    probabilities: probs,
    top_risk_factors: factors,
    feature_attributions: attributions,
    model_version: 'v1.0.0-rule-fallback',
    production_ready: false,
    fallback_used: true,
    model_limitation_notice: MODEL_LIMITATION_NOTICE,
    createdAt: new Date().toISOString(),
  };
}
