'use client';

import React, { useState } from 'react';
import { db } from '@/lib/store/mock-db';
import {
  BarChart3,
  TrendingUp,
  Download,
  AlertTriangle,
  ShieldCheck,
  Users,
  CheckCircle2,
  FileSpreadsheet,
  Cpu,
  Info,
} from 'lucide-react';

export default function HODAnalyticsPage() {
  const [selectedDimension, setSelectedDimension] = useState<'class' | 'subject' | 'teacher'>('class');

  const predictions = db.riskPredictions;
  const attempts = db.attempts;

  const lowRiskCount = predictions.filter((p) => p.risk_level.toLowerCase().includes('low')).length;
  const medRiskCount = predictions.filter((p) => p.risk_level.toLowerCase().includes('med')).length;
  const highRiskCount = predictions.filter((p) => p.risk_level.toLowerCase().includes('high')).length;

  // CSV Export Engine
  const handleExportCSV = () => {
    const headers = [
      'Student Name',
      'Class',
      'Average Score',
      'Recent Score',
      'Risk Classification',
      'Model Confidence',
      'Top Risk Factors',
    ];

    const rows = db.profiles
      .filter((p) => p.role === 'student')
      .map((st) => {
        const studentAttempts = attempts.filter((a) => a.studentId === st.id);
        const avg = studentAttempts.length
          ? Math.round(studentAttempts.reduce((s, a) => s + a.percentage, 0) / studentAttempts.length)
          : 80;
        const recent = studentAttempts.length ? studentAttempts[0].percentage : 82;
        const pred = predictions.find((p) => p.studentId === st.id) || {
          risk_level: 'Low Risk',
          confidence_score: 0.88,
          top_risk_factors: ['Consistent performance'],
        };

        return [
          `"${st.fullName}"`,
          '"Grade 10 Section A"',
          avg,
          recent,
          `"${pred.risk_level}"`,
          pred.confidence_score,
          `"${(pred.top_risk_factors || []).join('; ')}"`,
        ].join(',');
      });

    const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `edugap_department_academic_report_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 space-y-8 bg-slate-50 min-h-screen text-slate-900">
      {/* Header & CSV Export */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-black text-slate-900 sm:text-3xl font-heading">
            Department Analytics & Risk Matrix
          </h1>
          <p className="mt-1 text-xs sm:text-sm text-slate-600">
            Multi-dimensional comparative diagnostics, learning gap distribution, and PyTorch MLP attrition forecasting.
          </p>
        </div>

        <button
          onClick={handleExportCSV}
          className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-xs font-bold text-white shadow-md shadow-emerald-600/20 hover:bg-emerald-700 transition active:scale-95"
        >
          <Download className="h-4 w-4" />
          <span>Export Department Report (CSV)</span>
        </button>
      </div>

      {/* Mandatory Ethical AI Model Limitation Notice */}
      <div className="rounded-2xl border border-indigo-200 bg-indigo-50/70 p-5 shadow-xs">
        <div className="flex items-start gap-3 text-xs text-slate-700">
          <Info className="h-5 w-5 text-indigo-600 shrink-0 mt-0.5" />
          <div className="space-y-1 leading-relaxed">
            <strong className="text-slate-900 text-sm block font-heading">
              Institutional Ethical AI & Model Limitation Notice
            </strong>
            <p>
              Student academic risk predictions generated by the 4-layer PyTorch MLP neural network (
              <code className="text-indigo-700 font-mono font-bold bg-indigo-100/70 px-1 py-0.5 rounded">v1.0-mlp</code>) serve strictly as advisory decision-support signals for faculty counseling and remedial study planning. Under institutional academic policy, predictions <strong>must not</strong> automatically determine course grades, disciplinary sanctions, or admissions/dismissal determinations.
            </p>
          </div>
        </div>
      </div>

      {/* PyTorch MLP Risk Distribution Card */}
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2 font-heading">
            <Cpu className="h-4 w-4 text-indigo-600" />
            PyTorch MLP Student Risk Classification Distribution
          </h2>
          <span className="text-xs text-slate-500">Trained on UCI & OULAD-standardized indicators (95.2% Accuracy)</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {/* Low Risk */}
          <div className="rounded-xl border border-emerald-200 bg-emerald-50/70 p-4">
            <div className="flex items-center justify-between text-xs font-bold text-emerald-700 uppercase">
              <span>Low Risk</span>
              <span>{Math.round((lowRiskCount / (predictions.length || 1)) * 100)}%</span>
            </div>
            <div className="text-3xl font-black text-slate-900 mt-2 font-heading">{lowRiskCount} Students</div>
            <p className="text-[11px] text-slate-600 mt-1">High attendance &gt;90%, stable mastery</p>
          </div>

          {/* Medium Risk */}
          <div className="rounded-xl border border-amber-200 bg-amber-50/70 p-4">
            <div className="flex items-center justify-between text-xs font-bold text-amber-700 uppercase">
              <span>Medium Risk</span>
              <span>{Math.round((medRiskCount / (predictions.length || 1)) * 100)}%</span>
            </div>
            <div className="text-3xl font-black text-slate-900 mt-2 font-heading">{medRiskCount} Students</div>
            <p className="text-[11px] text-slate-600 mt-1">Borderline completion, minor gaps</p>
          </div>

          {/* High Risk */}
          <div className="rounded-xl border border-rose-200 bg-rose-50/70 p-4">
            <div className="flex items-center justify-between text-xs font-bold text-rose-700 uppercase">
              <span>High Risk</span>
              <span>{Math.round((highRiskCount / (predictions.length || 1)) * 100)}%</span>
            </div>
            <div className="text-3xl font-black text-slate-900 mt-2 font-heading">{highRiskCount} Student</div>
            <p className="text-[11px] text-slate-600 mt-1">Elevated integrity flags & late submissions</p>
          </div>
        </div>
      </div>

      {/* Comparative Cross-Section Dimension Selector */}
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2 font-heading">
            <BarChart3 className="h-4 w-4 text-purple-600" />
            Comparative Performance Analysis
          </h2>

          <div className="inline-flex rounded-xl bg-slate-100 p-1 border border-slate-200 text-xs">
            <button
              onClick={() => setSelectedDimension('class')}
              className={`rounded-lg px-3 py-1.5 font-bold transition ${
                selectedDimension === 'class'
                  ? 'bg-indigo-600 text-white shadow-xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              By Class
            </button>
            <button
              onClick={() => setSelectedDimension('subject')}
              className={`rounded-lg px-3 py-1.5 font-bold transition ${
                selectedDimension === 'subject'
                  ? 'bg-indigo-600 text-white shadow-xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              By Subject
            </button>
            <button
              onClick={() => setSelectedDimension('teacher')}
              className={`rounded-lg px-3 py-1.5 font-bold transition ${
                selectedDimension === 'teacher'
                  ? 'bg-indigo-600 text-white shadow-xs'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              By Teacher
            </button>
          </div>
        </div>

        {/* Dynamic Comparison Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          {selectedDimension === 'class' && (
            <>
              <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 space-y-2">
                <div className="flex justify-between font-bold text-sm text-slate-900 font-heading">
                  <span>Grade 10 - Section A</span>
                  <span className="text-indigo-700">65% Class Average</span>
                </div>
                <p className="text-slate-500">Prof. Sarah Jenkins &bull; 3 Active Students</p>
                <div className="pt-2 flex items-center justify-between text-slate-600">
                  <span>Completion Rate: 83.3%</span>
                  <span className="text-amber-700 font-semibold">4 Integrity Flags</span>
                </div>
              </div>

              <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 space-y-2">
                <div className="flex justify-between font-bold text-sm text-slate-900 font-heading">
                  <span>Grade 10 - Section B</span>
                  <span className="text-purple-700">72% Class Average</span>
                </div>
                <p className="text-slate-500">Prof. Marcus Sterling &bull; 28 Active Students</p>
                <div className="pt-2 flex items-center justify-between text-slate-600">
                  <span>Completion Rate: 91.0%</span>
                  <span className="text-emerald-700 font-semibold">1 Integrity Flag</span>
                </div>
              </div>
            </>
          )}

          {selectedDimension === 'subject' && (
            <>
              <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 space-y-2">
                <div className="flex justify-between font-bold text-sm text-slate-900 font-heading">
                  <span>Grade 10 Mathematics (MATH10)</span>
                  <span className="text-indigo-700">65% Subject Average</span>
                </div>
                <p className="text-slate-500">Core Curriculum &bull; 2 Published Diagnostics</p>
                <div className="pt-2 text-slate-600">Identified Deficit: Linear Word Problems (36%)</div>
              </div>

              <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 space-y-2">
                <div className="flex justify-between font-bold text-sm text-slate-900 font-heading">
                  <span>Advanced Linear Algebra (MATH12-ALG)</span>
                  <span className="text-purple-700">78% Subject Average</span>
                </div>
                <p className="text-slate-500">Elective Curriculum &bull; 4 Published Diagnostics</p>
                <div className="pt-2 text-slate-600">Identified Deficit: Vector Projections (62%)</div>
              </div>
            </>
          )}

          {selectedDimension === 'teacher' && (
            <>
              <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 space-y-2">
                <div className="flex justify-between font-bold text-sm text-slate-900 font-heading">
                  <span>Prof. Sarah Jenkins</span>
                  <span className="text-emerald-700">83.3% Assessment Completion</span>
                </div>
                <p className="text-slate-500">2 Active Assessments &bull; Grade 10 Section A</p>
                <div className="pt-2 text-slate-600">Class Average: 65.0%</div>
              </div>

              <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 space-y-2">
                <div className="flex justify-between font-bold text-sm text-slate-900 font-heading">
                  <span>Prof. David Kumar</span>
                  <span className="text-indigo-700">92.0% Assessment Completion</span>
                </div>
                <p className="text-slate-500">4 Active Assessments &bull; Grade 11 Calculus</p>
                <div className="pt-2 text-slate-600">Class Average: 74.5%</div>
              </div>
            </>
          )}
        </div>
      </div>

      {/* Production Launch Model Certification & Governance */}
      <div className="rounded-2xl border border-indigo-200 bg-white p-6 shadow-xs space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-slate-100 pb-5">
          <div className="flex items-center gap-3">
            <div className="rounded-xl bg-indigo-50 p-2.5 text-indigo-600 border border-indigo-100">
              <Cpu className="h-6 w-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-black text-slate-900 font-heading">
                  PyTorch MLP Production Model Governance
                </h2>
                <span className="rounded-full bg-emerald-50 px-2.5 py-0.5 text-[10px] font-bold text-emerald-700 border border-emerald-200 uppercase tracking-wide">
                  Launch Ready (v1.0.0)
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-0.5">
                4-Layer Regularized Multilayer Perceptron &bull; TorchScript JIT High-Throughput Serving &bull; Zero PII Pipeline
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3 text-xs">
            <span className="rounded-lg bg-slate-100 px-3 py-1 font-mono font-bold text-slate-700">
              Port: 8001 (FastAPI)
            </span>
            <span className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-50 px-3 py-1 font-bold text-emerald-700 border border-emerald-200">
              <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse"></span>
              Live & Healthy
            </span>
          </div>
        </div>

        {/* Model Metrics Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="rounded-xl border border-slate-100 bg-slate-50 p-4">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">Test Accuracy</span>
            <div className="mt-1 text-2xl font-black text-indigo-600 font-heading">96.98%</div>
            <span className="text-[10px] text-slate-500">Held-out 2,250 cohort records</span>
          </div>

          <div className="rounded-xl border border-slate-100 bg-slate-50 p-4">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">Macro F1 Score</span>
            <div className="mt-1 text-2xl font-black text-emerald-600 font-heading">0.9608</div>
            <span className="text-[10px] text-slate-500">High Risk Recall: 100.0%</span>
          </div>

          <div className="rounded-xl border border-slate-100 bg-slate-50 p-4">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">Inference Latency</span>
            <div className="mt-1 text-2xl font-black text-purple-600 font-heading">0.157 ms</div>
            <span className="text-[10px] text-slate-500">Sub-millisecond single inference</span>
          </div>

          <div className="rounded-xl border border-slate-100 bg-slate-50 p-4">
            <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">Throughput</span>
            <div className="mt-1 text-2xl font-black text-slate-800 font-heading">6,365/s</div>
            <span className="text-[10px] text-slate-500">Vectorized batch forwards</span>
          </div>
        </div>

        {/* Explainable AI Factor Weights */}
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3">
            Explainable AI (XAI) Risk Driver Attribution Weights
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
            <div className="rounded-lg border border-slate-100 bg-slate-50 p-3">
              <div className="flex justify-between font-bold text-slate-800">
                <span>Weak Curriculum Topics</span>
                <span className="text-indigo-600">30.4%</span>
              </div>
              <div className="mt-1.5 h-1.5 w-full bg-slate-200 rounded-full overflow-hidden">
                <div className="h-full bg-indigo-600 rounded-full" style={{ width: '30.4%' }}></div>
              </div>
            </div>

            <div className="rounded-lg border border-slate-100 bg-slate-50 p-3">
              <div className="flex justify-between font-bold text-slate-800">
                <span>Late Assignment Submissions</span>
                <span className="text-indigo-600">16.2%</span>
              </div>
              <div className="mt-1.5 h-1.5 w-full bg-slate-200 rounded-full overflow-hidden">
                <div className="h-full bg-indigo-600 rounded-full" style={{ width: '16.2%' }}></div>
              </div>
            </div>

            <div className="rounded-lg border border-slate-100 bg-slate-50 p-3">
              <div className="flex justify-between font-bold text-slate-800">
                <span>Anti-Cheat Integrity Incidents</span>
                <span className="text-indigo-600">15.2%</span>
              </div>
              <div className="mt-1.5 h-1.5 w-full bg-slate-200 rounded-full overflow-hidden">
                <div className="h-full bg-indigo-600 rounded-full" style={{ width: '15.2%' }}></div>
              </div>
            </div>
          </div>
        </div>

        {/* Ethical AI Notice */}
        <div className="rounded-xl border border-indigo-100 bg-indigo-50/50 p-3.5 flex items-start gap-2.5 text-xs text-indigo-900">
          <Info className="h-4 w-4 text-indigo-600 shrink-0 mt-0.5" />
          <p className="leading-relaxed">
            <strong>Advisory Model Notice:</strong> Student academic risk classifications generated by EdUGaP AI are advisory screening indicators designed for faculty guidance and proactive study plan personalization. Model predictions are strictly non-deterministic for grades or disciplinary sanctions.
          </p>
        </div>
      </div>
    </div>
  );
}
